# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'comfi' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for comfi
  pod 'Plaid'
  pod 'FBSDKLoginKit'
  pod 'Charts'

  target 'comfiTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'comfiUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
